name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.x  # Use the version of Ruby required for your Jekyll site

      - name: Install Bundler
        run: gem install bundler

      - name: Install Jekyll Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout --orphan gh-pages
          git reset --hard
          mv _site/* .
          rm -rf _site
          git add .
          git commit -m "Deploy Jekyll site to GitHub Pages"
          git branch -D main
          git branch -m main
          git push --force origin main gh-pages

      - name: Clean Up
        run: |
          git checkout main
          git branch -D gh-pages
